features:
  common: Fips
  data: industries
  naics: naics2
  path: https://raw.githubusercontent.com/ModelEarth/tree-canopy/refs/heads/main/inputs/features/combined_naics_data.csv
  state: all
folder: naics2-forestcanopy-counties-simple
models: rbf
targets:
  data: your_target_dataset
  path: https://raw.githubusercontent.com/ModelEarth/tree-canopy/refs/heads/main/input/targets/forest_canopy_data_target.csv
